### ISSUE TITLE
Allow backing storage as a string.

### ISSUE THREAD

**Issue by mtwilliams** [gjaldon/ecto_enum#4]
I was thinking of something like

``` elixir
defenum StatusEnum, ~w(registered active inactive archived minister_of_silly_walks)a
```

This way, I don't need to know the mapping when performing queries on dataset, i.e.

``` sql
-- John Cleese
SELECT * FROM users WHERE status = 'minister_of_silly_walks' LIMIT 1;
```

---

This is super-duper useful in a few situations:
- Ad-hoc querying for things like analytics and customer service.
- Multitenant databases. Especially when working in a polyglot (i.e. not using an umbrella app) microservices environment.
- Probably more!

Thoughts, @gjaldon?

**Comment by mtwilliams** [comment]
A cursory look over [`lib/ecto_enum.ex`](https://github.com/gjaldon/ecto_enum/blob/master/lib/ecto_enum.ex) has revealed two things:
1. It's not hard to toggle between an integer or string mapping; and
2. handling the difference between a list and keyword-list is only a minor inconvenience that necessitates minor refactoring.

Should I go ahead and submit a pull request implementing this functionality?

**Comment by azhi** [comment]
+1 for the feature.

My use-case is connecting Elixir (Ecto) app to existing DB that already uses string-based enum storage.

**Comment by gjaldon** [comment]
@mtwilliams allowing mapping to a string instead of an integer sounds good to me. Maybe even allow any value that Ecto accepts.

I prefer a keyword list to show the actual mapping since it is explicit. No need to guess what values the enums are mapped to in the db.

**Comment by mtwilliams** [comment]
You don't have to guess what they're mapped to if provided a list, as the in-memory and in-database values are the same. It's the equivalent of:

``` elixir
statuses = ~w(registered active inactive archived minister_of_silly_walks)a
defenum StatusEnum, Enum.zip(statuses, statuses)
```

Where as using a keyword-list opens you up to situations like so:

``` elixir
defenum InvoiceStatus, received: recieved
```

That can be hell when you're refactoring. Or if you're spelling impaired, like me.

**Comment by gjaldon** [comment]
I don't think the convenience is worth it. And why should the default mapping be to a string instead of an integer?

I think the verbosity of using a Keyword list, in this case, makes it easy to read definition of your enums in the future. You just quickly scan it and immediately know the values they map to in the DB. No need for additional effort to parse.

**Comment by JonnyPower** [comment]
+1 for this

**Comment by mtwilliams** [comment]
I've gone ahead and implemented this functionality. Please let me know what you think.

**Comment by mtwilliams** [comment]
Another improvement would be to provide a helper to assist in writing migrations when converting from integer backed to string backed enums (and vice versa).

**Comment by gjaldon** [comment]
> Another improvement would be to provide a helper to assist in writing migrations when converting from integer backed to string backed enums (and vice versa).

Shouldn't we encourage the use of integer-backed enums rather than string-backed ones? Storing integers in the DB is more space-efficient, I think and it's why Rails' enums is integer-backed. 

I'm thinking of supporting string-backed enums so that users can defer migrating their data to integer if they already started using strings. Maybe provide a helper for that instead?

**Comment by gjaldon** [comment]
Just added support for this in PR #77
